export const SET_TIMER_START = 'SET_TIMER_START';
export const SET_TIMER_SUCCESSS = 'SET_TIMER_SUCCESSS';
export const SET_TIMER_FAIL = 'SET_TIMER_FAIL';

export const ADD_TO_TIMER_CONTROL = 'ADD_TO_TIMER_CONTROL';
export const SUBTRACT_FROM_TIMER_CONTROL = 'SUBTRACT_FROM_TIMER_CONTROL';

export const START_TIMER = 'START_TIMER';
export const TIMER_DECREMENT = 'TIMER_DECREMENT';
export const PAUSE_TIMER = 'PAUSE_TIMER';
export const TIME_END = 'TIME_END';