export const SET_TIMER_START = 'SET_TIMER_START';
export const SET_TIMER_SUCCESSS = 'SET_TIMER_SUCCESSS';
export const SET_TIMER_FAIL = 'SET_TIMER_FAIL';

export const ADD_TO_TIMER_CONTROL = 'ADD_TO_TIMER_CONTROL';
export const SUBTRACT_FROM_TIMER_CONTROL = 'SUBTRACT_FROM_TIMER_CONTROL';